# Generated by Django 5.1.3 on 2024-12-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initail = True

    dependencies = [
    ]

    operations = [
        #gamerecord 테이블 생성
        migrations.CreateModel(
            name = 'GameRecord',
            fields = [
                ('id', models.AutoField(primary_key = True, serialize = False)),
                ('player_number', models.IntegerField()),
                ('player_dice_info', models.CharField(max_length=255)),
                ('player_total_score', models.IntegerField()),
                ('winner_player_number', models.IntegerField(null = True, blank = True)),
            ],
            options = {
                'db_table' : 'game_record',
            },
        ),
    ]
