# Generated by Django 5.1.3 on 2024-12-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerecord',
            old_name='player_dice_info',
            new_name='dice_values',
        ),
        migrations.RenameField(
            model_name='gamerecord',
            old_name='player_total_score',
            new_name='game_id',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='winner_player_number',
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
