# Generated by Django 5.1.3 on 2024-12-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fruit_name", models.CharField(max_length=255)),
                ("fruit_number", models.IntegerField()),
            ],
            options={
                "db_table": "FruitMart",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("buyNumber", models.IntegerField()),
                (
                    "fruitNumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_orders",
                        to="fruit_mart.mart",
                    ),
                ),
                (
                    "fruitType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fruit_orders",
                        to="fruit_mart.mart",
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
